defmodule PhoenixPaper.Icon do
  @moduledoc """
  A thin wrapper around the heroicon classes that `mix phx.new` already
  vendors into every Phoenix 1.7+ app (`assets/vendor/heroicons` + the
  Tailwind heroicons plugin generated by the installer).

  PhoenixPaper does **not** ship its own icon set or extra dependency: pass
  the same `hero-*` class you'd use with the app's default `core_components`
  icon helper (e.g. `"hero-check"`, `"hero-check-solid"`, `"hero-check-mini"`).
  """
  use Phoenix.Component

  alias PhoenixPaper.Helpers

  attr(:name, :string, required: true, doc: ~s(a heroicon class, e.g. "hero-check"))
  attr(:paperize, :boolean, default: true)
  attr(:class, :any, default: nil)

  @doc "Renders a heroicon. See the module doc."
  def pp_icon(assigns) do
    ~H"""
    <span
      data-pp-component="icon"
      class={Helpers.classes(@paperize, "inline-block size-5 align-[-0.125em]", [@name, @class])}
    />
    """
  end
end
